### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by vincenzogianfelice** [drygdryg/OneShot#10]
Hi. When i try to launch it this error appears:

```
[*] Running wpa_supplicant...
Traceback (most recent call last):
  File "./oneshot.py", line 739, in <module>
    connect(options, data)
  File "./oneshot.py", line 430, in connect
    wpas = run_wpa_supplicant(options)
  File "./oneshot.py", line 281, in run_wpa_supplicant
    proc = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, encoding='utf-8')
TypeError: __init__() got an unexpected keyword argument 'encoding'
```

**Comment by drygdryg** [comment]
Python 3.6 and above is reqiured. Please check your Python version.
