### ISSUE TITLE
cant use OneShot after reset

### ISSUE THREAD

**Issue by catnoee** [drygdryg/OneShot#80]
[*] Running wpa_supplicant…
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/OneShot/oneshot.py", line 1201, in <module>
    companion = Companion(args.interface, args.write, print_debug=args.verbose)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/OneShot/oneshot.py", line 416, in __init__
    self.__init_wpa_supplicant()
  File "/data/data/com.termux/files/home/OneShot/oneshot.py", line 445, in __init_wpa_supplicant
    raise ValueError('wpa_supplicant returned an error: ' + self.wpas.communicate()[0])
ValueError: wpa_supplicant returned an error: CANNOT LINK EXECUTABLE "wpa_supplicant": library "libssl.so.3" not found: needed by main executable

Exception ignored in: <function Companion.__del__ at 0x7cde4122a0>
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/OneShot/oneshot.py", line 828, in __del__
    self.cleanup()
  File "/data/data/com.termux/files/home/OneShot/oneshot.py", line 821, in cleanup
    self.retsock.close()
    ^^^^^^^^^^^^
AttributeError: 'Companion' object has no attribute 'retsock'

**Comment by eda-abec** [comment]
You don't have libssl.so.3. Try installing openssl package.
