### ISSUE TITLE
Can i use this on macbook m1?

### ISSUE THREAD

**Issue by MrKira34** [drygdryg/OneShot#81]
How can I use it?
MacBook Pro M1

**Comment by MrKira34** [comment]
```
$ sudo python3 OneShot/oneshot.py -i lo0 -K
Password:
Executing: /usr/bin/sudo /sbin/ifconfig lo0 up

[*] Running wpa_supplicant…
Traceback (most recent call last):
  File "/Users/mrkira/OneShot/oneshot.py", line 1201, in <module>
    companion = Companion(args.interface, args.write, print_debug=args.verbose)
  File "/Users/mrkira/OneShot/oneshot.py", line 416, in __init__
    self.__init_wpa_supplicant()
  File "/Users/mrkira/OneShot/oneshot.py", line 445, in __init_wpa_supplicant
    raise ValueError('wpa_supplicant returned an error: ' + self.wpas.communicate()[0])
ValueError: wpa_supplicant returned an error: /bin/sh: wpa_supplicant: command not found

Exception ignored in: <function Companion.__del__ at 0x10101f760>
Traceback (most recent call last):
  File "/Users/mrkira/OneShot/oneshot.py", line 828, in __del__
    self.cleanup()
  File "/Users/mrkira/OneShot/oneshot.py", line 821, in cleanup
    self.retsock.close()
AttributeError: 'Companion' object has no attribute 'retsock'
```

**Comment by MrKira34** [comment]
How to install wpa_supplicant on MacBook M1?
